config/routes.rb
DribbbleTest::Application.routes.draw do
  
  resources :users do
    member do
      get 'picture'
    end
    collection do
      get 'like_pic'
    end
  end
  resources :user_sessions
  resource :dashboard, :controller => 'dashboard', :only => "show"
  
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  root :to => 'user_sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation, :pic
  has_many :user_likes
  
  has_attached_file :pic, 
        :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
        :url => "/system/:attachment/:id/:style/:filename",
        :styles => { :normal => "400x300", :thumb => "30x30" }
  #validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
  
  acts_as_authentic
end

app/models/user_like.rb
class UserLike < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :liked_user_id

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

    private

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
    
    def require_user
      unless current_user
        store_location
        flash[:notice] = t('sessions.require_user')
        redirect_to login_url
        return false
      end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_user
  def show
    @users = User.all(:conditions => ["pic_file_name is not null and id != (?)", current_user.id])
    @user_likes = current_user.user_likes.map(&:liked_user_id)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  # GET /user_sessions/new
  # GET /user_sessions/new.xml
  def new
    @user_session = UserSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_session }
    end
  end

  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])

    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(dashboard_path, :notice => 'Login Successful') }
        format.xml  { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  
  def picture
    @user = User.find(params[:id])
  end
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def like_pic
    user_id = Rails.env == 'test' ? User.first.id : current_user.id
    UserLike.create(:user_id => user_id, :liked_user_id => params[:liked_user_id])
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/show.html.erb
<div id="pics_container">
  <% @users.each do |user| %>
    <div class="pic_container">
      <%= image_tag user.pic.url(:normal) %>
      <br />
      by <%= user.username %>
      <% if !@user_likes.include?(user.id) %> 
        <%= link_to 'Like', "javascript: like(#{user.id})", :id => "like_#{user.id}" %>
        <span class='liked' id='liked_<%= user.id %>'>Liked</span>
      <% else %>
        <span class='liked_before'>Liked</span>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  function like(id){
    $.ajax({
      url: '<%= like_pic_users_path %>',
      data: { liked_user_id: id }
    }).done(function() {
      $('#like_'+id).hide();
      $('#liked_'+id).show();
    });
  }
</script>

<style>
  .liked{
    display: none;
    color: red;
  }
  .liked_before{
    color: red;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dribbble Test</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <% if current_user %>
          <%= link_to "Dribbble Test", dashboard_path, :class => "brand" %>
        <% else %>
          <%= link_to "Dribbble Test", root_path, :class => "brand" %>
        <% end %>
        <div class="nav-collapse">
          <ul class="nav">
            <% if current_user %>
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Upload picture", picture_user_path(current_user) %></li>
            <% end %>
          </ul>
          <div id="user_nav">
            <% if current_user %>
              <span class="white">Logged in as <%= current_user.username %></span>
              <span>
                <%= link_to "(Edit Profile)", edit_user_path(current_user.id)%> |
                <%= link_to "Logout", :logout %>
              </span>
            <% else %>
              <span>
                <%= link_to "Register", new_user_path%> | 
                <%= link_to "Login", :login %>
              </span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
</body>
</html>

app/views/session/edit.html.erb
<%= render :partial => 'form' %>

app/views/session/new.html.erb
<%= render :partial => 'form' %>

app/views/user_sessions/_form.html.erb
<%= form_for @user_session, :html => { :class => 'form-horizontal' } do |f| %>
<% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

    <ul>
    <% @user_session.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<fieldset>
  <legend>Log in or create a new user!</legend>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label'  %>
      <div class="controls">
        <%= f.text_field :username %>
      </div>
  </div>
  
  <div class="control-group">
    <%= f.label :password, :class => 'control-label'  %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Log in", :class => "btn btn-primary" %> or <%= link_to "Register", new_user_path, :class => "btn" %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<h1>Welcome to Ridddle test</h1>
<%= render 'form' %>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user_session from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> User</legend>

    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', users_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.username, user_path(user) %></td>
        <td><%= user.created_at %></td>
        <td>
          <% if current_user == user %>
            <%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-mini' %>
            <%= link_to 'Destroy', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_user_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%= render :partial => 'form' %>

app/views/users/picture.html.erb
<fieldset>
  <legend>Upload a picture</legend>
  <%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="control-group">
      <%= f.label :pic, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :pic, :class => 'text_field' %>
      </div>
    </div>
    
    <div class="form-actions">
      <%= f.submit "Upload Pic", :class => 'btn btn-primary' %>
    </div> 
  <% end %>

</fieldset>

app/views/users/show.html.erb
<h1>User</h1>

<p>
  <b>Username</b><br>
  <%= @user.username %>
  <%= image_tag @user.pic.url(:thumb) unless @user.pic_file_name.nil? %>
</p>

<p>
  <b>Email</b><br>
  <%= @user.email %>
</p>

<div class="form-actions">
  <%= link_to 'Edit', edit_user_path(@user), :class => 'btn' %>
  <%= link_to 'Delete', user_path(@user), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>